apiVersion: v1
kind: Service
metadata:
  name: go-con-client-2
  labels:
    app: go-con-client-2
spec:
  type: NodePort
  ports:
    - port: 8082
      targetPort: 8082
      name: config-client
    - port: 8081
      targetPort: 8081
      name: app
  selector:
    app: go-con-client-2